### ISSUE TITLE
`extends` setting in tsconfig.ts can cause functions container to fail

### ISSUE THREAD

**Issue by elitan** [nhost/cli#305]
The functions container will fail trying to start with the following `tsconfig.ts`:

```json
{
  "extends": "../../config/tsconfig.base.json",
  "include": ["src"],
}
```

This is the `tsconfig.ts` file we're using in our monorepo for our `@nhost/hasura-storage-js` package [here](https://github.com/nhost/nhost/blob/fix/storage-in-node/packages/hasura-storage-js/tsconfig.json#L2).

The reason functions fails is because we mount the current directory so the functions container can not find the file at `../.../config/tsconfig.base.json`.

<details>
<summary>Here's the logs from the functions container:</summary>

```text
hasura-storage-js-laughing_lumiere-functions-1  | [nodemon] 2.0.19
hasura-storage-js-laughing_lumiere-functions-1  | [nodemon] to restart at any time, enter `rs`
hasura-storage-js-laughing_lumiere-functions-1  | [nodemon] watching path(s): *.*
hasura-storage-js-laughing_lumiere-functions-1  | [nodemon] watching extensions: json,yaml,lock
hasura-storage-js-laughing_lumiere-functions-1  | [nodemon] starting `cd $FUNCTIONS_WORKING_DIR ; ni ; nodemon --ext 'js,ts' -w $FUNCTIONS_RELATIVE_PATH -x 'tsx' $SERVER_PATH/server.ts ./package.json`
hasura-storage-js-laughing_lumiere-functions-1  |  ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In : No matching version found for @nhost/core@* inside the workspace
hasura-storage-js-laughing_lumiere-functions-1  | [nodemon] 2.0.19
hasura-storage-js-laughing_lumiere-functions-1  | [nodemon] to restart at any time, enter `rs`
hasura-storage-js-laughing_lumiere-functions-1  | [nodemon] watching path(s): functions/**/*
hasura-storage-js-laughing_lumiere-functions-1  | [nodemon] watching extensions: js,ts
hasura-storage-js-laughing_lumiere-functions-1  | [nodemon] starting `tsx /server.ts ./package.json`
hasura-storage-js-laughing_lumiere-functions-1  | Error: File '../../config/tsconfig.base.json' not found.
hasura-storage-js-laughing_lumiere-functions-1  |     at x (file:///usr/local/lib/node_modules/tsx/node_modules/get-tsconfig/dist/index.mjs:3:4891)
hasura-storage-js-laughing_lumiere-functions-1  |     at M (file:///usr/local/lib/node_modules/tsx/node_modules/get-tsconfig/dist/index.mjs:3:6256)
hasura-storage-js-laughing_lumiere-functions-1  |     at ie (file:///usr/local/lib/node_modules/tsx/node_modules/get-tsconfig/dist/index.mjs:3:7250)
hasura-storage-js-laughing_lumiere-functions-1  |     at file:///usr/local/lib/node_modules/tsx/node_modules/@esbuild-kit/esm-loader/dist/index.js:1:476
hasura-storage-js-laughing_lumiere-functions-1  |     at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
hasura-storage-js-laughing_lumiere-functions-1  |     at async Loader.import (internal/modules/esm/loader.js:178:24)
hasura-storage-js-laughing_lumiere-functions-1  |     at async internal/process/esm_loader.js:57:9
hasura-storage-js-laughing_lumiere-functions-1  |     at async Object.loadESM (internal/process/esm_loader.js:67:5)
hasura-storage-js-laughing_lumiere-functions-1  |     at async handleMainPromise (internal/modules/run_main.js:59:12)
hasura-storage-js-laughing_lumiere-functions-1  | [nodemon] app crashed - waiting for file changes before starting...
hasura-storage-js-laughing_lumiere-functions-1 exited with code 137
```

</details>

A side effect of functions not being able to start is that the CLI can never complete its startup sequence because the final step is to ensure all containers (including the functions container) are healthy. 

Relevant [PR](https://github.com/nhost/nhost/pull/893) and [GitHub Action that times out](https://github.com/nhost/nhost/runs/7990786445?check_suite_focus=true#step:5:133).

**Comment by elephant3** [comment]
Fixed in https://github.com/nhost/cli/releases/tag/v0.7.8 release
