### ISSUE TITLE
Running nhost dev after CLI update: 'Processing...' indefinitely before it fails

### ISSUE THREAD

**Issue by founderpad** [nhost/cli#393]
I upgraded to the latest CLI, and now get this when I run a nhost dev:

```
> It takes longer than usual to start your Nhost project. Most likely because of the need to install your npm dependencies. Please wait.
> Processing...

> Processing...

...

Failed to start services
[context deadline exceeded] Failed to start services
```

If I do a `nhost logs -f` I get the following output:

```
coral-great_pascal-functions-1       | [nodemon] watching extensions: js,ts
coral-great_pascal-functions-1       | [nodemon] starting `tsx /server.ts ./functions/package.json`
coral-great_pascal-functions-1       | (node:83) UnhandledPromiseRejectionWarning: Error: Cannot find module 'functions'
coral-great_pascal-functions-1       | Require stack:
coral-great_pascal-functions-1       | - /opt/project/functions/boost/approve-boost-comment.js
coral-great_pascal-functions-1       |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
coral-great_pascal-functions-1       |     at Function.u.default._resolveFilename (/usr/local/lib/node_modules/tsx/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:1486)
coral-great_pascal-functions-1       |     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
coral-great_pascal-functions-1       |     at Module.require (internal/modules/cjs/loader.js:974:19)
coral-great_pascal-functions-1       |     at require (internal/modules/cjs/helpers.js:101:18)
coral-great_pascal-functions-1       |     at Object.<anonymous> (/opt/project/functions/boost/approve-boost-comment.js:1:59)
coral-great_pascal-functions-1       |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
coral-great_pascal-functions-1       |     at Object.v (/usr/local/lib/node_modules/tsx/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:933)
coral-great_pascal-functions-1       |     at Module.load (internal/modules/cjs/loader.js:950:32)
coral-great_pascal-functions-1       |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
coral-great_pascal-functions-1       | (Use `node --trace-warnings ...` to show where the warning was created)
coral-great_pascal-functions-1       | (node:83) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
coral-great_pascal-functions-1       | (node:83) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
coral-great_pascal-functions-1       | [nodemon] clean exit - waiting for changes before restart
coral-great_pascal-minio-1           | MinIO Object Storage Server
coral-great_pascal-minio-1           | Copyright: 2015-2022 MinIO, Inc.
coral-great_pascal-minio-1           | License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
coral-great_pascal-minio-1           | Version: RELEASE.2022-07-08T00-05-23Z (go1.18.3 linux/arm64)
coral-great_pascal-minio-1           | 
coral-great_pascal-minio-1           | Status:         1 Online, 0 Offline. 
coral-great_pascal-minio-1           | API: http://0.0.0.0:9000 
coral-great_pascal-minio-1           | Console: http://0.0.0.0:8484 
coral-great_pascal-minio-1           | 
coral-great_pascal-minio-1           | Documentation: https://docs.min.io
coral-great_pascal-minio-1           | 
coral-great_pascal-minio-1           |  You are running an older version of MinIO released 3 months ago 
coral-great_pascal-minio-1           |  Update: Run `mc admin update` 
coral-great_pascal-minio-1           | 
coral-great_pascal-minio-1           | 
coral-great_pascal-storage-1         | problem reading : Config File "hasura-storage" Not Found in "[/]"
```

Interestingly, Docker Desktop shows all the containers as "Running" which is confusing.

Here is the `package.json` inside `functions`:

```
{
	"name": "functions",
	"version": "1.0.0",
	"description": "Serverless functions for frontend",
	"scripts": {
		"test": "yarn test"
	},
	"author": "founderpad",
	"license": "ISC",
	"dependencies": {
		"aws-sdk": "^2.1231.0",
		"express": "^4.18.2",
		"graphql": "^16.6.0",
		"graphql-request": "^5.0.0",
		"onesignal-node": "^3.4.0"
	},
	"devDependencies": {
		"@aws-sdk/types": "^3.55.0",
		"@types/aws-sdk": "^2.7.0",
		"@types/express": "^4.17.14",
		"@types/node": "^18.8.3",
		"dotenv": "^16.0.3",
		"typescript": "^4.8.4"
	}
}
```

There are also errors saying tables exist etc:

```
coral-great_pascal-graphql-engine-1  | {"detail":{"http_info":{"content_encoding":null,"http_version":"HTTP/1.1","ip":"172.18.0.8","method":"POST","status":400,"url":"/v1/metadata"},"operation":{"error":{"code":"already-exists","error":"field with name \"provider\" already exists in table \"auth.user_providers\"","path":"$.args"},"request_id":"4694ee03-5858-4a7f-a971-c2361d2342d2","request_mode":"error","response_size":128,"user_vars":{"x-hasura-role":"admin"}},"request_id":"4694ee03-5858-4a7f-a971-c2361d2342d2"},"level":"error","timestamp":"2022-10-11T08:42:30.402+0000","type":"http-log"}
coral-great_pascal-graphql-engine-1  | {"detail":{"http_info":{"content_encoding":null,"http_version":"HTTP/1.1","ip":"172.18.0.8","method":"POST","status":400,"url":"/v1/metadata"},"operation":{"error":{"code":"already-exists","error":"field with name \"user\" already exists in table \"auth.refresh_tokens\"","path":"$.args"},"request_id":"40e52813-158f-423a-a71e-adb6ead01c9b","request_mode":"error","response_size":124,"user_vars":{"x-hasura-role":"admin"}},"request_id":"40e52813-158f-423a-a71e-adb6ead01c9b"},"level":"error","timestamp":"2022-10-11T08:42:30.402+0000","type":"http-log"}
```

This all worked fine up until 4 days ago when I upgraded everything.

**Comment by elitan** [comment]
@founderpad Would you mind sharing how you fixed this issue? It can be helpful fo the next developer who faces the same problem.

**Comment by benorudolf** [comment]
Adding a potential solution for anyone stumbling upon this: 

Had the same issue started happening all of a sudden when running `nhost dev` or `nhost up`.  
The line `> Processing...` would just keep repeating. All docker services were running successfully.

The problem for me was that I had an issue in my cloud functions. I left a test local file import in one of the functions (file was outside the functions folder), which was causing nodemon to crash i.e. _crash and waiting for file changes before restarting._ 

When I removed the import everything started working again. Not sure why, but it seems that crashing the nodemon during startup might be causing this.

**Comment by brian-lim-42** [comment]
> Adding a potential solution for anyone stumbling upon this:
> 
> Had the same issue started happening all of a sudden when running `nhost dev` or `nhost up`. The line `> Processing...` would just keep repeating. All docker services were running successfully.
> 
> The problem for me was that I had an issue in my cloud functions. I left a test local file import in one of the functions (file was outside the functions folder), which was causing nodemon to crash i.e. _crash and waiting for file changes before restarting._
> 
> When I removed the import everything started working again. Not sure why, but it seems that crashing the nodemon during startup might be causing this.

Confirmed, thanks!
